version: '3.8'

services:

  vault:
    image: hashicorp/vault
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    links:
      - "consul:consul"
  consul:
    image: hashicorp/consul
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.hcl
    volumes:
      - ./consul/config/config.hcl:/consul/config/config.hcl
      - ./consul/data:/consul/data
